import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';

import { SafeHtmlPipe } from './safe-html.pipe';


import {
  NavbarModule, 
  WavesModule,
  PreloadersModule,
  InputsModule,
  InputUtilitiesModule,
  ModalModule,
  ChartsModule,
  TabsModule,
  DatepickerModule,
  SelectModule,
  ButtonsModule,
  ChartSimpleModule,
  AccordionModule,
  CollapseModule,
  TooltipModule,
  DropdownModule,
  CardsModule,
  LightBoxModule,
  CharCounterModule,
  CarouselModule,
  BadgeModule,
  IconsModule,
  ChipsModule,
  AutoCompleterModule,
  SidenavModule,
  CheckboxModule,
  TableModule,
  TimePickerModule,
  FileInputModule,
  StepperModule,
  PopoverModule} from 'ng-uikit-pro-standard'; 


@NgModule({
  declarations: [SafeHtmlPipe],
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    HttpClientModule,
    PreloadersModule,
    NavbarModule,
    ChartsModule,
    DatepickerModule,
    SelectModule,
    ChartSimpleModule,
    AccordionModule,  
    LightBoxModule,
    WavesModule,
    InputsModule,
    InputUtilitiesModule,
    ModalModule,
    TabsModule,
    ButtonsModule,
    TooltipModule,
    CollapseModule,
    DropdownModule,
    CardsModule,
    CharCounterModule,
    CarouselModule,
    BadgeModule,
    IconsModule,
    ChipsModule,
    AutoCompleterModule,
    SidenavModule,
    CheckboxModule,
    TableModule,
    TimePickerModule,
    FileInputModule,
    StepperModule
  ],
  exports:[
    CommonModule,
    FormsModule,
    SafeHtmlPipe,
    ReactiveFormsModule,
    HttpClientModule,
    PreloadersModule,
    NavbarModule,
    ChartsModule,
    DatepickerModule,
    SelectModule,
    ChartSimpleModule,
    AccordionModule,  
    LightBoxModule,
    WavesModule,
    InputsModule,
    InputUtilitiesModule,
    ModalModule,
    TabsModule,
    ButtonsModule,
    TooltipModule,
    CollapseModule,
    DropdownModule,
    CardsModule,
    CharCounterModule,
    CarouselModule,
    BadgeModule,
    IconsModule,
    ChipsModule,
    AutoCompleterModule,
    SidenavModule,
    CheckboxModule,
    TableModule,
    TimePickerModule,
    FileInputModule,
    StepperModule,
    PopoverModule
  ]
})
export class SharedModule { }
